# Parameters of the Seq2Seq Model

# Device-sensitive parameters
amr_data_dir: &amr_data_dir data/steady
glove: &glove /home/sheng/data/glove/glove.840B.300d.zip


# Model parameters
model:
  model_type: STOG
  use_char_cnn: True
  use_coverage: False
  use_bert: True

  bert:
    pretrained_model_dir: /home/sheng/data/bert-base-cased
    hidden_size: 768

  encoder_token_embedding:
    num_embeddings:
    vocab_namespace: 'encoder_token_ids'
    embedding_dim: 300
    padding_index: 0
    dropout: 0
    pretrained_file:

  encoder_pos_embedding:
    num_embeddings:
    vocab_namespace: 'pos_tags'
    embedding_dim: 50
    padding_index: 0
    dropout: 0

  encoder_char_embedding:
    num_embeddings:
    vocab_namespace: 'encoder_token_characters'
    embedding_dim: &encoder_char_embedding_dim 50
    padding_index: 0
    dropout: 0
    pretrained_file:

  encoder_char_cnn:
    embedding_dim: *encoder_char_embedding_dim
    num_filters: 50
    ngram_filter_sizes: [3]

  decoder_token_embedding:
    num_embeddings:
    vocab_namespace: 'decoder_token_ids'
    embedding_dim: 300
    padding_index: 0
    dropout: 0
    pretrained_file:

  decoder_pos_embedding:
    num_embeddings:
    vocab_namespace: 'pos_tags'
    embedding_dim: 50
    padding_index: 0
    dropout: 0

  decoder_char_embedding:
    num_embeddings:
    vocab_namespace: 'decoder_token_characters'
    embedding_dim: &decoder_char_embedding_dim 50
    padding_index: 0
    dropout: 0
    pretrained_file:

  decoder_coref_embedding:
    num_embeddings: 500
    embedding_dim: 50
    padding_index: 0
    dropout: 0

  decoder_char_cnn:
    embedding_dim: *decoder_char_embedding_dim
    num_filters: 50
    ngram_filter_sizes: [3]

  encoder:
    input_size:
    hidden_size: 256
    num_layers: 2
    use_highway: False
    dropout: 0

  decoder:
    input_size:
    hidden_size: &decoder_hidden_size 512
    num_layers: 2
    use_highway: False
    dropout: 0

  source_attention:
    attention_function: dot
    share_linear: False
    coverage: False

  coref_attention:
    attention_function: dot
    share_linear: True

  generator:
    input_size: *decoder_hidden_size
    # Specify vocab_size and pad_idx dynamically
    vocab_size:
    pad_idx:
    force_copy: True

  graph_decoder:
    decode_algorithm: 'greedy'
    input_size: 512
    edge_node_hidden_size: 200
    edge_label_hidden_size: 100
    dropout: 0

  mimick_test:
    data: data/steady/dev_amr.txt.features.preproc
    prediction: prediction-in-train.txt
    batch_size: 32
    eval_script: scripts/eval_test.sh
    smatch_dir: tools/amr-evaluation-tool-enhanced
    word_splitter: /home/sheng/data/bert-base-cased/bert-base-cased-vocab.txt


# Data parameters
data:
  data_dir: *amr_data_dir
  train_data: dev_amr.txt.features.preproc
  dev_data: dev_amr.txt.features.preproc
  test_data: dev_amr.txt.features.preproc
  data_type: AMR
  batch_first: True
  train_batch_size: &train_batch_size 16
  test_batch_size: 32
  iter_type: BucketIterator
  pretrain_token_emb: *glove
  pretrain_char_emb:
  word_splitter: /home/sheng/data/bert-base-cased/bert-base-cased-vocab.txt


# Training parameters
environment:
  recover: True
  seed: 1
  numpy_seed: 1
  torch_seed: 1
  serialization_dir: &serialization_dir debug-ckpt
  file_friendly_logging: False
  gpu: True
  cuda_device: 0

trainer:
  device: # No need to be specified, will be updated at runtime
  # Optimizer
  no_grad: []
  optimizer_type: adam
  learning_rate: 0.001
  max_grad_norm: 5.0
  batch_size: *train_batch_size
  shuffle: True
  epochs: 50
  dev_metric: +F1
  serialization_dir: *serialization_dir
  model_save_interval:

test:
  evaluate_on_test: True
